version = 1
SPDX-PackageName = "the-last-eichhof"
SPDX-PackageSupplier = "Friedrich von Never <friedrich@fornever.me>"
SPDX-PackageDownloadLocation = "https://github.com/ForNeVeR/the-last-eichhof"

[[annotations]]
path = "*.DotSettings"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Friedrich von Never <friedrich@fornever.me>"
SPDX-License-Identifier = "MIT"
